name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Connect to VM and perform actions
        run: |
          ssh denzelnasol@35.197.116.127 "cd investing-simulator; git pull origin production; pm2 restart app"

    # steps:
    #   - name: Connect to VM
    #     run: ssh denzelnasol@35.197.116.127 "cd investing-simulator"

    #   - name: Pull changes
    #     run: ssh denzelnasol@35.197.116.127 "git pull origin production"

    #   # - name: Copy environment files
    #   #   run: |
    #   #     ssh denzelnasol@35.197.116.127 "cp /path/to/.env.production /path/to/your/node/app/.env"

    #   - name: Restart Node app with PM2
    #     run: ssh denzelnasol@35.197.116.127 "pm2 restart app"